name: flutter_bmflocation
description: BaiduMapLocation plugin for flutter. This plugin provides a cross-platform (iOS, Android) API to request location.
version: 1.0.4
homepage: https://lbsyun.baidu.com/index.php?title=flutter/loc

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.4
  permission_handler: ^9.2.0

  flutter_baidu_mapapi_base:
    path: ../flutter_baidu_mapapi_base-2.0.1

  flutter_baidu_mapapi_map:
    path: ../flutter_baidu_mapapi_map-2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package:  com.baidu.bdmap_location_flutter_plugin
        pluginClass: LocationFlutterPlugin
      ios:
        pluginClass: LocationFlutterPlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
